name: mifadeschats
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.4
  firebase_storage: ^3.1.1
  image_cropper: 1.0.2
  image_picker: 0.6.0+17
  intl: ^0.16.1
  uuid: 2.0.4
  intro_views_flutter: ^2.8.0

  google_sign_in: ^4.0.7
  flutter_facebook_login: ^3.0.0
  provider: ^4.0.4
  cloud_firestore: ^0.12.9+5
  firebase_auth_web: ^0.1.2

  lottie: ^0.2.1
  flutter_bloc: ^3.2.0
  animated_text_kit: ^2.0.0
  flutter_slidable: "^0.5.4"
  flutter_gradients: ^0.0.3
  curved_navigation_bar: ^0.3.2
  equatable: ^1.1.0
  bloc: ^3.0.0
  page_transition: "^1.1.5"
  switches_kit: ^0.0.1
  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/images/google-logo.png
   - assets/images/facebook-logo.png
   - assets/images/cat-male.png
   - assets/images/cat-female.png
   - assets/lottie/bad-cat.json
   - assets/lottie/angry-cat.json
   - assets/lottie/loading-cat.json

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/Apercu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Apercu-Light.ttf
          weight: 300
        - asset: assets/fonts/Apercu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Apercu-Italic.ttf
          style: italic
        - asset: assets/fonts/Apercu-Medium.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
