name: mifadeschats
description: Une application pour les chats

version: 1.0.0+4

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  ## Data Management
  get_it: ^4.0.1
  provider: ^4.0.4

  ## Service
  shared_preferences: ^0.5.6+3
  uuid: ^2.0.4
  flutter_local_notifications: ^1.4.0
  flutter_secure_storage: ^3.3.1+1
  intl: ^0.16.1
  image_picker: 0.6.0+17
  pin_view: ^1.0.1


  ## UI
  flare_flutter: ^2.0.1
  curved_navigation_bar: ^0.3.2
  lottie: ^0.3.3
  animated_text_kit: ^2.0.0
  flutter_slidable: ^0.5.4
  simple_animations: ^1.3.8
  calendar_strip: ^1.0.6
  pimp_my_button: ^1.0.0

  ## Firestore
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.5
  firebase_dynamic_links: ^0.5.0+1
  rxdart: ^0.23.0


  # from dependencie 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/google-logo.png
   - assets/images/facebook-logo.png
   - assets/images/apple-logo.png
   - assets/images/cat-male.png
   - assets/images/cat-female.png
   - assets/animation/lottie/bad-cat.json
   - assets/animation/lottie/angry-cat.json
   - assets/animation/lottie/loading-cat.json
   - assets/animation/lottie/waiting-cat.json
   - assets/animation/lottie/email-cat.json
   - assets/animation/rive/loading-cat.flr
   - assets/animation/rive/bad-cat.flr
   - assets/animation/rive/angry-cat.flr

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/Apercu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Apercu-Light.ttf
          weight: 300
        - asset: assets/fonts/Apercu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Apercu-Italic.ttf
          style: italic
        - asset: assets/fonts/Apercu-Medium.ttf
